---
title: "Homework"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    toc-location: body
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

## Homeworks

| Homework | Assignment | Assignment due (\@11pm) | Answers | Solutions (`.qmd`) | Solutions (`.html`)\* |
|----------|----------|----------|----------|----------------|-----------------|
| 0 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_00.qmd)]{style="color:#f8f5f0;"} | `r hw0` | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 1 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_01.qmd)]{style="color:#f8f5f0;"} | `r hw1` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_01_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_01/HW_01_solns.qmd?csf=1&web=1&e=iLkbC1)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_01/HW_01_solns.html?csf=1&web=1&e=JsCX6z)]{style="color:#f8f5f0;"} |
| 2 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_02.qmd)]{style="color:#f8f5f0;"} | `r hw2` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_02_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_02/HW_02_solns_incomplete.qmd?csf=1&web=1&e=4NbX8t)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_02/HW_02_solns_incomplete.html?csf=1&web=1&e=VIzT5L)]{style="color:#f8f5f0;"} |
| 3\* | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_03.qmd)]{style="color:#f8f5f0;"} | `r hw3` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_03_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_03/HW_03_solns_incomplete.qmd?csf=1&web=1&e=ISmKDd)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_03/HW_03_solns_incomplete.html?csf=1&web=1&e=hEMF2e)]{style="color:#f8f5f0;"} |
| 4 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_04.qmd)]{style="color:#f8f5f0;"} | `r hw4` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_04_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_04/HW_04_solns_incomplete.qmd?csf=1&web=1&e=fQdcBF)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_04/HW_04_solns_incomplete.html?csf=1&web=1&e=g7Faui)]{style="color:#f8f5f0;"} |
| 5 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_05.qmd)]{style="color:#f8f5f0;"} | `r hw5` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_05_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_05/HW_05_solns.qmd?csf=1&web=1&e=WJeSJV)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_05/HW_05_solns.html?csf=1&web=1&e=UYgaoq)]{style="color:#f8f5f0;"} |
| 6\* | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_06.qmd)]{style="color:#f8f5f0;"} | `r hw6` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_06_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_06/HW_06_solns_incomplete.qmd?csf=1&web=1&e=FvKGHZ)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_06/HW_06_solns_incomplete.html?csf=1&web=1&e=dtOkQY)]{style="color:#f8f5f0;"} |
| 7 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_07.qmd)]{style="color:#f8f5f0;"} | `r hw7` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_07_ans.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify icon-park-twotone file-code size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_07/HW_07_solns_incomplete_F24.qmd?csf=1&web=1&e=uhdKMy)]{style="color:#f8f5f0;"} | [[{{< iconify mingcute web-fill size=29px >}}](https://ohsuitg-my.sharepoint.com/:u:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/HW_solns/HW_07/HW_07_solns_incomplete_F24.html?csf=1&web=1&e=Y7V3Qu)]{style="color:#f8f5f0;"} |
| 8 | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_08.qmd)]{style="color:#f8f5f0;"} | `r hw8` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_08_ans.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 9 (optional) | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_09.qmd)]{style="color:#f8f5f0;"} | `r hw9` | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_09_ans.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |

Please note that you need to download the `.html` file to see the LaTeX math properly.

## File Naming

-   For HW **Assignments**, please use the following file naming: "HW01_LastName_FirstInitial"

    -   For homeworks without R, this should be a pdf file

    -   For homeworks with R, this may be a pdf file (with the code in the pdf) or an html file

## Rubric

### Assignments

A total of 1 point will be given for a complete homework. The following rubric will be used:

|   | 1 point | 0 points |
|------------------------|------------------------|------------------------|
| Completeness | All problems and parts (like a, b, c, etc.) are thoroughly attempted. Answers can be incorrect or correct. For parts with longer processes and calculations, solution set up and calculations are required. | Entire problems or parts are skipped. -OR- The full process of a problem is not completed through the calculation. |
