---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 30px;
  color: #3070BF;
  background-color: #fff;
  padding: 0px;
}
```

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

| Week | Date | Les-son | Topic | TB sections | Key Info | Slides HTML | Slides PDF | Slides Notes | Exit tix | Record-ing | Muddy Points |
|------|------|------|------|------|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | 0 | Welcome |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Welcome/00_Welcome_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Welcome/00_Welcome.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Welcome/00_Welcome.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOE1SSDdDSzVNTUJKMVRSWVNXOTAwM001QyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/00_Welcome.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=PqBXON)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 1 | Data collection | 1.3 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Data_collection/01_Data_collection.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Data_collection/01_Data_collection.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/01_Data_collection/01_Data_collection_notes.pdf)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/01_Data_collection_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=jfcie9)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/01_Data_collection_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=8BQeQB)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/01_Data_collection/01_Data_collection_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | 2 | Intro to data & numerical summaries | 1.2, 1.4 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMkY1N0RVSDQ0U0xTWVJNOVJWUklEU0ZXTiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/02_Intro_data_num_summaries.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=U3YpWL)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw0 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 0 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | 3 | Defining Probability | 2.1 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/03_Probability/03_Probability_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Probability/03_Probability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_Probability/03_Probability.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/03_Probability/03_Probability_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNFlFUDczT0YyNUxUMUFZTFlISlYzMFk5SyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/03_Probability.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=IyG23p)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/03_Probability/03_Probability_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R01* | *Download R and RStudio* |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/R01_Download_R/R01_Download_R.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/R01_Download_R/R01_Download_R.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/R01_Download_R/R01_Download_R_notes.qmd)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R01_Intro_R.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ktZuTH)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w2d2 %>% format("%m/%d")` | 4 | Conditional Probability | 2.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/04_Cond_prob/04_Cond_prob_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Cond_prob/04_Cond_prob.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_Cond_prob/04_Cond_prob.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/04_Cond_prob/04_Cond_prob_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1lLNksyOVJBT0k4WVE0RVlIMVhaS09NQyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/04_Cond_prob.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=DNcPK6)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/04_Cond_prob/04_Cond_prob_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R02* | *R Basics, pt 1* |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R02_Basics_01/R02_Basics_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R02_Basics_01/R02_Basics_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R01_R02_R_Basics.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=PyIxx5)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/R02_Basics_01/R02_Basics_01_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw1 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 1 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 3 | `r w3d1 %>% format("%m/%d")` | 5 | Random variables, Binomial distribution | 3.1-3.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1JUS0ZOQ0c4MUIzOUJGWDIxTTdXV1dWVCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/05_RVs_Binomial_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=XwoTmX)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R03* | *R Basics, pt 2* |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R02_Basics_01/R02_Basics_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R02_Basics_01/R02_Basics_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R01_R02_R_Basics.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=PyIxx5)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R02_R_Basics_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=U2XpJa)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/R02_Basics_01/R02_Basics_01_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w3d2 %>% format("%m/%d")` | 5 | Random variables, Binomial distribution, continued | 3.1-3.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURFM4RzlOTEhYODEyMlZTVkxVVThHM05NSCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/05_RVs_Binomial.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=cdV8q4)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/05_RVs_Binomial_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ne1MkY)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R04* | *Reproducibility, File Organization, and Projects* |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R04_Reproducibility/R04_Reproducibility.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R04_Reproducibility/R04_Reproducibility.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R04_Reproducibility.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=MdUXb1)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | *R05* | *Intro to Quarto, packages, and importing data* |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R05_Quarto_01/R05_Quarto_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R05_Quarto_01/R05_Quarto.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R05_Quarto_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=Qa5Dnf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw2 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 2 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 4 | `r w4d1 %>% format("%m/%d")` | 6 | Normal distribution | 3.3 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/06_Normal/06_Normal_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_Normal/06_Normal.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/06_Normal/06_Normal.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/06_Normal/06_Normal_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1JVOUtBVERYQktUODRaNkMzSUNDU1YySiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/06_Normal.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=eUrVmI)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/06_Normal/06_Normal_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w4d2 %>% format("%m/%d")` | *R05* | *Intro to Quarto, packages, and importing data, continued* |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/R05_Quarto_01/R05_Quarto_01_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R05_Quarto_01/R05_Quarto_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R05_Quarto_01/R05_Quarto.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUM0FNSzMzRVlNMkhNOUdTR09NWERWMVVFTyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R05_Quarto_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=Qa5Dnf)]{style="color:#f8f5f0;"} [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R05_Quarto_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=qJfZ4l) | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | *R06* | *`ggplot`* |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R06_ggplot_01/R06_ggplot_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R06_ggplot_01/R06_ggplot_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R06_ggplot2.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3Mh5Qu)]{style="color:#f8f5f0;"} |  |
|  |  | 8 | Data visualization of a single variable | 1.5-1.7 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_Data_visualization_01/08_Data_visualization_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_Data_visualization_01/08_Data_visualization_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/08_Data_visualization_01/08_Data_visualization_01_notes.pdf)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/08_Data_viz_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=TaveVR)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q1_open %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 1 opens \@ 3pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r hw3 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 3 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r q1_close %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 1 closes \@11pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 5 | `r w5d1 %>% format("%m/%d")` | 7 | Poisson distribution | 3.4 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/07_Poisson/07_Poisson_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_Poisson/07_Poisson.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_Poisson/07_Poisson.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/07_Poisson/07_Poisson_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNFVBNVZCWDlBVTBLQ1A2SkZYWThBREtCNSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/07_Poisson.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=7nNabQ)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 9 | Data visualization of two variables | 1.5-1.7 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_Data_visualization_02/09_Data_visualization_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_Data_visualization_02/09_Data_visualization_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/09_Data_visualization_02/09_Data_visualization_02_notes.pdf)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/09_Data_viz_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=TIWdoE)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w5d2 %>% format("%m/%d")` | 10 | Variability in estimates | 4.1 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/10_Variability/10_Variability_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Variability/10_Variability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_Variability/10_Variability.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/10_Variability/10_Variability_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMzY0RUdMUzQyVE81Ulc0R0xYUDRQOFVJUiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/10_Variability.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=u8NJgb)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/10_Variability/10_Variability_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R07* | *LaTeX in Quarto* |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R07_LaTeX/R07_LaTeX.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R07_LaTeX/R07_LaTeX.pdf)]{style="color:#f8f5f0;"} |  |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R07_LaTeX.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=rGgVak)]{style="color:#f8f5f0;"} |  |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 4 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [[**Midterm Feedback form due \@ 11pm**](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMk44UkxXTlVBTFBBUkc5UE9FUkdZVUdJNCQlQCNjPTEu)]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 6 | `r w6d1 %>% format("%m/%d")` | 11 | Confidence Intervals | 4.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/11_Confidence_intervals/11_Confidence_intervals_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Confidence_intervals/11_Confidence_intervals.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Confidence_intervals/11_Confidence_intervals.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Confidence_intervals/11_Confidence_intervals_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQTdISVBKN1FYRFNTSVpKV0VVOUhaS1JNSCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/11_Confidence_intervals.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=XikFi6)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/11_Confidence_intervals/11_Confidence_intervals_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w6d2 %>% format("%m/%d")` | 12 | Hypothesis Testing 1: Single-sample mean | 4.3, 5.1 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/12_Hyp_testing_01/12_Hyp_testing_01_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Hyp_testing_01/12_Hyp_testing_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/12_Hyp_testing_01/12_Hyp_testing_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/12_Hyp_testing_01/12_Hyp_testing_01_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMDdCWFBMNTlNVklPWDRZWEhERkM2SFNHUCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/12_Hyp_testing_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=VVLyFe)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/12_Hyp_testing_01/12_Hyp_testing_01_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw5 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 5 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 7 | `r w7d1 %>% format("%m/%d")` | 13 | Inference for mean difference from two-sample dependent/paired data (Hypothesis Testing 2) | 5.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/13_Hyp_testing_02/13_Hyp_testing_02_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Hyp_testing_02/13_Hyp_testing_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/13_Hyp_testing_02/13_Hyp_testing_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/13_Hyp_testing_02/13_Hyp_testing_02_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ0kzOThTVllMTTZBSldaUURBQllZMDVBMiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/13_Hyp_testing_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=L3hZGf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/13_Hyp_testing_02/13_Hyp_testing_02_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R08* | *Transforming and subetting data with `tidyverse`*, part 1 |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.pdf)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R08_tidyverse_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=0BgHY0) [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R08_tidyverse_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=AFaA4B)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w7d2 %>% format("%m/%d")` | 14 | Inference for difference in means from two independent samples (Hypothesis Testing 3) | 5.3 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/14_Hyp_testing_03/14_Hyp_testing_03_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Hyp_testing_03/14_Hyp_testing_03.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/14_Hyp_testing_03/14_Hyp_testing_03.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/14_Hyp_testing_03/14_Hyp_testing_03_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMFdXMDExSFE4NkRZQ0FJSVhOU1NTN0wxNSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/14_Hyp_testing_03.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=W0YK1X)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/14_Hyp_testing_03/14_Hyp_testing_03_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  | *R08* | *Transforming and subetting data with `tidyverse`* , part 2 |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.pdf)]{style="color:#f8f5f0;"} |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R08_tidyverse_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=0BgHY0) [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/R08_tidyverse_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=AFaA4B)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r q2_open %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 2 opens \@ 3pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r hw6 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 6 due \@ 11pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r q2_close %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 2 closes \@ 11pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 8 | `r w8d1 %>% format("%m/%d")` | 15 | Power and sample size calculations for means | 5.4 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/15_Power_sample_size/15_Power_sample_size_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_Power_sample_size/15_Power_sample_size.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/15_Power_sample_size/15_Power_sample_size.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/15_Power_sample_size/15_Power_sample_size_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURThQMjFJVEYxODNNQkhTRU41R0xKTUJLQyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/EPI_525_25F/Student_files_EPI_525/Recordings/15_PSS.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=OYDFow)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/15_Power_sample_size/15_Power_sample_size_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w8d2 %>% format("%m/%d")` | 16 | Comparing Means with ANOVA | 5.5 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/16_ANOVA/16_ANOVA_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/16_ANOVA/16_ANOVA.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/16_ANOVA/16_ANOVA.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTlLWklaQ1ZGOElaNFhaNk8xQlg1SlVRRiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw7 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 7 due \@ 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 9 | `r w9d1 %>% format("%m/%d")` | 17 | Inference for a single proportion or difference in proportions | 8.1-8.2 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_Prop_inference/17_Prop_inference.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w9d2 %>% format("%m/%d")` |  | No class |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 10 | `r w10d1 %>% format("%m/%d")` | 18 | Chi-squared tests, Fishers exact test | 8.3-8.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_Chi_sq_Fisher/18_Chi_sq_Fisher.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w10d2 %>% format("%m/%d")` | 19 | Non-parametric tests | Other TB | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/19_Non_parametric/19_Non_parametric.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | *R09* | *Summarizing data with `tidyverse`* and Table 1 |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw8 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**HW 8 due 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 11 | `r w11d1 %>% format("%m/%d")` | 20 | Simple Linear Regression | 6.1-6.4 | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/20_SLR_01/20_SLR_01.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q3_open %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 3 opens \@ 3pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | `r w11d2 %>% format("%m/%d")` |  | Class if needed |  |  |  |  |  |  |  |  |
|  | [**`r hw9 %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Optional HW 9 due 11 pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |
|  | [**`r q3_close %>% format("%m/%d")`**]{style="color:#3070BF;"} |  | [**Quiz 3 closes \@ 11pm**]{style="color:#3070BF;"} |  |  |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 46,6, 6, 6, 6, 6,6, 6\]"}
