---
title: "Homework 3"
subtitle: "Lessons 5"
author: "Your name here - update this!!!!"
description: "Due: `r library(here); source(here('class_dates.R')); hw3 %>% format('%m/%d')` at 11pm"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    self-contained: true
    html-math-method: mathjax
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)

library(here)
source(here("class_dates.R"))
```

## Directions {.unnumbered}

**Please turn in this homework on Sakai.** Please submit your homework in pdf format if you are not rendering a Quarto document. **If you are using a Quarto doc to render your full homework, then you can keep it as an html!** You can type your work on your computer or submit a single file with photos of your written work or any other method that can be turned into a pdf. The Adobe Scan phone app is an easy way to scan photos and compile into a PDF. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

You can download the .qmd file for this assignment from [Github](https://github.com/nwakim/EPI_525_25F/blob/main/homework/HW_03.qmd) if you want to work in a Quarto doc. **You do not need to work in a Quarto doc for this homework!!**


:::{.callout-important}
* The non-R exercises may be completed not using Quarto. I especially recommend writing out by hand the chapter 3 probability questions, whether on paper or a tablet.
    * _Some problems involve R code to calculate a probability, but the code is brief and you can write out the code and the answer by hand if you want._
    * You can also have all your R code together at the end of your homework file
* If you are completing the homework on paper, you can use a scanning app, such as Adobe Scan or iPhone notes, to create a pdf of your assignment.
:::

# Book exercises {.unnumbered}

## 3.5 Gull clutch size {.unnumbered}

::: callout-important
Note that the solutions in the back of the book are not quite right. For part (a), the answer is correct, but there is an error in the work and the notation is sloppy. For part (b), the answer is _not_ correct, as a result of the error in the work for part (a).
:::

For part b, you can assume the seagulls are independent!

## 3.6 Scooping ice cream  {.unnumbered}

Assume all random varibles are independent.

## 3.8 Chickenpox, Part I.  {.unnumbered}

For #3.8, you can use R functions to calculate the binomial probabilities instead of directly using the formula. However, include the mathematical formulas that would be used to calculate the probabilities.


## 3.10 Chickenpox, Part II.  {.unnumbered}

For #3.10, you can use R functions to calculate the binomial probabilities instead of directly using the formula. However, include the mathematical formulas that would be used to calculate the probabilities.






