---
title: "Muddy Points"
subtitle: "Lesson 2: Intro to data & numerical summaries"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Fall 2025

### 1. Why is median and IQR more accurate for samples with extreme values and why not use it for every sample if that's the case?

The median and IQR are less influenced by extreme values, so they give a better sense of the "typical" value when there are outliers. This is because the median is the middle value when all values are ordered, so extreme values do not affect it as much as they do the mean. **The order of the values matter more than the value itself, so if a value is in the top 50% of values it does not matter whether it is extreme or not.** The IQR measures the spread of the middle 50% of the data, so it also is less affected by extreme values.

We do not universally use median and IQR because of a few hand-wavy things: built-up stat theory, historical precedent, and familiarity. The mean and standard deviation are more commonly used in many fields, so people are more familiar with them. Additionally, the mean and standard deviation have nice mathematical properties that make them easier to work with in some statistical analyses.

### 2. How do we know when to use mean vs. median? and standard deviation vs. variance vs. IQR?

In general, your default should be mean and standard deviation. If you have reason to believe that your data is **really** skewed or has outliers, then consider using median and IQR instead. Because mean and standard deviation are embedded in statistical analysis so much, we really need to be compelled to use median and IQR. 

For standard deviation vs variance, standard deviation is in the same units as the data, so it is often easier to interpret. Variance is in squared units, which can be harder to understand. However, variance is used in many statistical analyses because it has nice mathematical properties. So again, default to standard deviation unless you have a specific reason to use variance.


## Fall 2024

### 1. Coming back to mathematical notation

Thank you for reminding me of this!! I will be more explicit with defining all the components of equations. (In one of the below links, they do a pretty good job explaining the math components.)

### 2. Standard deviation

Okay, so I could try to explain this a little more, but honestly there are some pretty good videos out there. Here are a few! 

- [StatQuest](https://www.youtube.com/watch?v=SzZ6GpcfoQY&ab_channel=StatQuestwithJoshStarmer)
  - The first 5 minutes will cover the intuition behind standard deviation, but the whole video is pretty great!
  - At about 4:30, they explain the equation for population variance
    - Might be helpful in the $\Sum$ in our standard deviation equation was confusing!
- [DATAtab](https://www.youtube.com/watch?v=5wJUUgnMGWA&ab_channel=DATAtab)
  - I like how they step through the example in this one!
- [Another one](https://www.youtube.com/watch?v=MRqtXL2WX2M&ab_channel=JeremyBlitz-Jones)
  - Not my favorite, but the shortest!
  - Gives pretty good incentive for why we use the standard deviation!

#### I think conceptualizing the standard deviation on an image of the graphs. This was confusing as some of the standard deviation's went from the middle bar to last bar (sd1 and sd2) whereas one graph show the sd going from the middle bar to not quite the last bar (sd 3) on slide "Measures of spread: standard deviation (SD) (1/3)"

This wasn't clear in the lesson, but I was taking example observations, then just showing you the deviation for each of those example observations. It does not matter which ones I showed, but the average of all the observations' deviances that matters! 

### 3. What benefit would the median provide, especially if the mean would be more representative of the entire dataset including any outliers? Is this relating directly to how you mentioned that some people choose to not include outliers (also I thought that was being selective to data to leave out data points)?

Okay, good question! First, the mean would not really be "more representative" of the data. It just represents something different than the median. Both are aiming to summarize the center of the data. So if we have one observation that is an outlier, but the rest of the group is pretty condensed, then which measure best represents the center of the data? The mean does not do a very good job of identifying where most observations are, but the median captures the center much better.

Honestly, I would not dwell on removing outliers. Many statisticians would agree that we do not remove outliers to make our mean a better representation. And in general, it's not a good idea to use math as the evidence to make the math better. Ya know?

