---
title: "Key Info and Announcements"
subtitle: "Lesson 2: Introduction to data & numerical summaries"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- Campus safety: Since we are on the PSU campus, please take a look at some of the Student Resources for PSU campus safety: <https://www.pdx.edu/dean-student-life/student-resources>
  - Our classroom does not require badge access - if you ever feel unsafe, the 5th and 6th floors require badges

### MPH Practice Experience Information 

All MPH programs require a Practice Experience (PE). 

The PE is your opportunity to take the knowledge and skills from your MPH coursework and apply them to public health topics in workplace settings. You must complete all 5 core MPH courses (Intro/Est. and Hypothesis Testing for Applied Biostatistics, Epidemiology I, Concepts of Environmental Health, Health Systems Organization, Principles of Health Behavior). Students in the Biostats program need additional BSTA coursework, and Epi program students need EPI Data (EPI 536). 

We highly recommend MPH students start searching for their PEs two terms in advance—one term to search and confirm your PE, the second term to draft and finalize your PE Learning Agreement—because students are expected to find their PEs. The PE is 4 credits, which translates to 160 contact hours. PEs can be completed over 1, 2, or more terms, and we highly recommend (but not require) students do their PEs over *two* terms. For the PE, students must produce two deliverables that demonstrate five competencies ([CEPH MPH Foundational Competency #6](https://ohsu-psu-sph.org/degree-programs/master-public-health/foundational-competencies/), two additional CEPH MPH Foundation Competencies, and two program competencies). 

Students are required to attend a PE Info Session. For more details on preparing for, finding, details of the Practice Experience, and upcoming PE/IP Info Session, visit (and bookmark!) the SPH PE’s webpage at <https://ohsu-psu-sph.org/applied-learning-experience/practice-experience>.

## Key Dates