---
title: "Key Info and Announcements"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- Naming files
  - When inserting an image, make sure your file names do not include things like `.` or `#` or other symbols
    - Best practice is to only include `_` and `-` and letters and numbers
- Check out the homework answers!!
- Homework 4
  - `lower.tail = T` vs `lower.tail = F`
    - In `p____()` (like `pbinom()`)...
        - `lower.tail=T` gives us $P(X \leq q)$ 
        - `lower.tail=F` gives us $P(X > q)$ 
  - Importing your dataset: will go over again today
- Week of thanksgiving: all office hours are cancelled
  - Email the TAs for questions! 

### Free Biostatistics Peer Tutoring Available Starting November 17th! 

We have had a little delay with onboarding new peer-tutors this year, but Charles Parker will be available starting November 17th to support folks with biostatistics! 

Unlike TAs, tutors are not closely associated with any particular course sections or professors, nor do they have any grading responsibilities. Consider meeting with a tutor when you feel stuck on a project, need help with R coding, want to review course concepts, or simply complete assignments in a social learning environment. There is no cost to use tutoring. ​

Charles is looking forward to working with you in a one-to-one or group setting, depending on your needs. Starting November 17th, [you will be able to schedule to meet with them.](https://traccloud.go-redrock.com/ohsu)   

You can contact  the Academic Success Center with questions learningsupport@ohsu.edu.​


## Key Dates

- [Quiz 2](https://nwakim.github.io/EPI_525_25F/quiz.html#quiz-2) opens on Wednesday and due Sunday
- Homework 6 due Sunday